export { default as trashcanSVG } from './svg/trashcan';
export { default as pencilSVG } from './svg/pencil';
export { default as links } from './links';
export { default as homeIcon } from './svg/home';
export { default as quote } from './svg/quotes';
export { default as search } from './svg/search';
export { default as stock } from './svg/stock';
export { default as termites } from './svg/termites';
export { default as addIcon } from './svg/add';